name: bookmi_app
description: BookMi - Marketplace de rÃ©servation de talents
version: 1.0.0+4
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.38.1

dependencies:
  bloc: ^9.2.0
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  url_launcher: ^6.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  go_router: ^17.1.0
  google_fonts: ^8.0.0
  hive_ce: ^2.19.0
  hive_ce_flutter: ^2.3.0
  intl: ^0.20.2
  sentry_dio: ^9.13.0
  sentry_flutter: ^9.13.0
  shimmer: ^3.0.0
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^18.0.1
  font_awesome_flutter: ^10.12.0
  image_picker: ^1.1.2
  paystack_flutter_sdk: ^0.0.1-alpha.2
  webview_flutter: ^4.10.0
  path_provider: ^2.1.5
  open_filex: ^4.4.1
  uuid: ^4.5.1
  package_info_plus: ^9.0.0
  share_plus: ^12.0.1
  record: ^6.2.0
  just_audio: ^0.10.5
  geolocator: ^13.0.2

dev_dependencies:
  bloc_lint: ">=0.3.3 <0.3.6"
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.20
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
